# Generated by Django 2.0.1 on 2018-01-30 13:30

import buddhalow.util
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.CharField(default=buddhalow.util.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.CharField(default=buddhalow.util.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddhalow.Dimension')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.CharField(default=buddhalow.util.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('probability', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddhalow.Dimension')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('probability', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddhalow.Dimension')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddhalow.Opportunity')),
            ],
        ),
    ]
