# Generated by Django 2.0.1 on 2018-01-30 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddhalow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='status',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='buddhalow.Status'),
        ),
    ]
