# Generated by Django 2.0.1 on 2018-01-30 18:02

import buddhalow.util
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddhalow', '0002_auto_20180130_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aqtivity',
            fields=[
                ('id', models.CharField(default=buddhalow.util.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('aqtivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_aqtivity_id', to='buddhalow.Aqtivity')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='aqtivity',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddhalow.Facility'),
        ),
        migrations.AddField(
            model_name='aqtivity',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddhalow.Sport'),
        ),
    ]
