# Generated by Django 2.0.1 on 2018-01-30 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddhalow', '0003_auto_20180130_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='aqtivity',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buddhalow.Status'),
            preserve_default=False,
        ),
    ]
