# Generated by Django 2.0.1 on 2018-01-30 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddhalow', '0005_auto_20180130_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='aqtivity',
            name='dimension',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buddhalow.Dimension'),
            preserve_default=False,
        ),
    ]
