# Generated by Django 2.0.1 on 2018-01-31 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddhalow', '0006_aqtivity_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitystate',
            name='status',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='buddhalow.Status'),
        ),
    ]
