# Generated by Django 2.0.1 on 2018-01-31 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddhalow', '0007_opportunitystate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
